#!/usr/bin/env ruby

if ARGV.length > 0
  print "[Help] Unnecessary argument. Run as: ./disc_golf_course_tracker"
else
  puts <<EOS
What would you like to do?

1. Add a course to you Wish List
2. View your course Wish List
3. Remove a course from your Wish List
4. View your played courses
5. Review a played course
6. Import Data
EOS
end